### PR TITLE
Adding in error event emission

### PR DESCRIPTION
**Pull request by JamiesonRoberts**
@estrattonbailey I've added in what I think is the correct line as per #16 

I decided to raise the actual error into the state object to ensure that it can be passed along with whatever logging system is being used.

Give this a look, and once its good to go I'll update the docs!

### CODE REVIEW

**Comment by estrattonbailey** [comment]
Nice! Thanks for doing this! Good call on passing the error.

Now that I see this, do you think it's a problem that the last error will persist in state? Since it's synchronous, I think we could do:
```javascript
evx.emit('error', { error: e })
evx.hydrate({ error: undefined }) // clear error
```

This might require a slight update to `evx` as well, but I can handle that. Thoughts?

**Comment by JamiesonRoberts** [comment]
@estrattonbailey I think that makes sense, the nice thing about that is that it also then avoids the consumer having to worry about clearing it.

**Comment by JamiesonRoberts** [comment]
@estrattonbailey Added in!

**Comment by JamiesonRoberts** [comment]
@estrattonbailey Hi Eric, i'm sorry for not following up sooner, got buried on other work. I've tested things as best I can with this approach on my side, i was wondering if you could take a look and see if there were any further changes you need made to the PR. if not, let me know if there is anything you need me to do to help with the release!

Cheers!

**Comment by estrattonbailey** [comment]
@JamiesonRoberts published a patch, `3.4.1`. Thanks for your help!

**Pull request merged**
