### PR TITLE
update evx and picostate dependencies

### PR DESCRIPTION
**Pull request by nikrowell**
Depends on [evx PR #8](https://github.com/estrattonbailey/evx/pull/8)

### CODE REVIEW

**Comment by estrattonbailey** [comment]
Thanks man! Really appreciate you working on these things :)

I messed this one up though too, since picostate isn't used in this library anymore. I guess I forgot to update the deps.

Before I continue to forget for a week, I just made these few updates and pushed a new minor and patch version. So 3.6.1 should be good to go.

Again, sorry I messed this one up. Thanks for your help!

**Comment by nikrowell** [comment]
@estrattonbailey all good - thanks for making these great tools available - happy to contribute!

**Comment by nikrowell** [comment]
Hi Eric - I'm running picoapp `3.6.1` and it doesn't appear that the [evx transient data](https://github.com/estrattonbailey/evx/pull/7) updates are there. Did we overlook a dependency update or am I missing something? Thanks for the help!

**Comment by estrattonbailey** [comment]
@nikrowell really no excuse for my delay other than I def saw this and then lost this in my notifications months ago. Really sorry.

Another person hit me up about this same issue which jogged my memory. I rebuilt both libraries and published patches. Can you try 3.6.2 and see if that works? If you haven't abandoned this effort entirely in the intervening months 😬

**Comment by nikrowell** [comment]
@estrattonbailey no problem at all. Just tested things out and seems to working as expected - thank you!

**Pull request closed without merging**
